[package]
org = "ballerina"
name = "constraint"
version = "1.0.2"
authors = ["Ballerina"]
keywords = ["constraint", "validation"]
repository = "https://github.com/ballerina-platform/module-ballerina-constraint"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.2.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "constraint-native"
version = "1.0.2"
path = "../native/build/libs/constraint-native-1.0.2-SNAPSHOT.jar"
